export const catalog = [
  {
    "title": "jujutsu-kaisen",
    "name": "jujutsu-kaisen",
    "href": "/animes/jujutsu-kaisen",
    "cover": "/covers/animes/jujutsu-kaisen.jpeg",
    "mp4Count": 185,
    "scenePacksCount": 185,
    "type": "anime",
    "latestUpdatedAt": 1775609558862,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "kakegurui",
    "name": "kakegurui",
    "href": "/series/kakegurui",
    "cover": "/covers/series/kakegurui.jpeg",
    "mp4Count": 31,
    "scenePacksCount": 31,
    "type": "series",
    "latestUpdatedAt": 1775609558863,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "outer-banks",
    "name": "outer-banks",
    "href": "/series/outer-banks",
    "cover": "/covers/series/outer-banks.jpeg",
    "mp4Count": 2,
    "scenePacksCount": 2,
    "type": "series",
    "latestUpdatedAt": 1775609558863,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "squid-game",
    "name": "squid-game",
    "href": "/series/squid-game",
    "cover": "/covers/series/squid-game.jpeg",
    "mp4Count": 21,
    "scenePacksCount": 21,
    "type": "series",
    "latestUpdatedAt": 1775609558865,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "stranger-things",
    "name": "stranger-things",
    "href": "/series/stranger-things",
    "cover": "/covers/series/stranger-things.jpeg",
    "mp4Count": 19,
    "scenePacksCount": 19,
    "type": "series",
    "latestUpdatedAt": 1775609558868,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "the-vampire-diaries",
    "name": "the-vampire-diaries",
    "href": "/series/the-vampire-diaries",
    "cover": "/covers/series/the-vampire-diaries.jpeg",
    "mp4Count": 5,
    "scenePacksCount": 5,
    "type": "series",
    "latestUpdatedAt": 1775609558868,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "wednesday",
    "name": "wednesday",
    "href": "/series/wednesday",
    "cover": "/covers/series/wednesday.jpeg",
    "mp4Count": 44,
    "scenePacksCount": 44,
    "type": "series",
    "latestUpdatedAt": 1775609558873,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "10-things-i-hate-about-you",
    "name": "10-things-i-hate-about-you",
    "href": "/movies/10-things-i-hate-about-you",
    "cover": "/covers/movies/10-things-i-hate-about-you.jpeg",
    "mp4Count": 3,
    "scenePacksCount": 3,
    "type": "movie",
    "latestUpdatedAt": 1775609558873,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "challengers",
    "name": "challengers",
    "href": "/movies/challengers",
    "cover": "/covers/movies/challengers.jpeg",
    "mp4Count": 4,
    "scenePacksCount": 4,
    "type": "movie",
    "latestUpdatedAt": 1775609558874,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "culpa-mia",
    "name": "culpa-mia",
    "href": "/movies/culpa-mia",
    "cover": "/covers/movies/culpa-mia.jpeg",
    "mp4Count": 5,
    "scenePacksCount": 5,
    "type": "movie",
    "latestUpdatedAt": 1775609558875,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "culpa-nuestra",
    "name": "culpa-nuestra",
    "href": "/movies/culpa-nuestra",
    "cover": "/covers/movies/culpa-nuestra.jpeg",
    "mp4Count": 4,
    "scenePacksCount": 4,
    "type": "movie",
    "latestUpdatedAt": 1775609558875,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "culpa-tuya",
    "name": "culpa-tuya",
    "href": "/movies/culpa-tuya",
    "cover": "/covers/movies/culpa-tuya.jpeg",
    "mp4Count": 1,
    "scenePacksCount": 1,
    "type": "movie",
    "latestUpdatedAt": 1775609558876,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "miller's-girl",
    "name": "miller's-girl",
    "href": "/movies/miller's-girl",
    "cover": "/covers/movies/miller's-girl.jpeg",
    "mp4Count": 4,
    "scenePacksCount": 4,
    "type": "movie",
    "latestUpdatedAt": 1775609558876,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "the-fallout",
    "name": "the-fallout",
    "href": "/movies/the-fallout",
    "cover": "/covers/movies/the-fallout.jpeg",
    "mp4Count": 7,
    "scenePacksCount": 7,
    "type": "movie",
    "latestUpdatedAt": 1775609558877,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "twilight",
    "name": "twilight",
    "href": "/movies/twilight",
    "cover": "/covers/movies/twilight.jpeg",
    "mp4Count": 4,
    "scenePacksCount": 4,
    "type": "movie",
    "latestUpdatedAt": 1775609558878,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  },
  {
    "title": "winter-spring-summer-or-fall",
    "name": "winter-spring-summer-or-fall",
    "href": "/movies/winter-spring-summer-or-fall",
    "cover": "/covers/movies/winter-spring-summer-or-fall.jpeg",
    "mp4Count": 3,
    "scenePacksCount": 3,
    "type": "movie",
    "latestUpdatedAt": 1775609558878,
    "flags": {
      "is4k": true,
      "is1080p": true,
      "isBR": true,
      "isJP": true,
      "isUS": true,
      "isBestScenes": true,
      "isMelhoresCenas": true,
      "isAllScenes": true,
      "isTodasAsCenas": true
    },
    "blobUrl": "",
    "monetizedUrl": ""
  }
];