export type PackCatalogItem = {
  mediaType: "anime" | "series" | "movie";
  mediaSlug: string;
  title: string;
  character: string;
  language: string;
  season: string;
  pack: string;
  file: string;
  href: string;
  fileSizeBytes: number;
  fileSizeText: string;
  updatedAt: number;
  updatedAtText: string;
  isMonetized: boolean;
};

export const packsCatalog: PackCatalogItem[] = [
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Atsuya Kusakabe - melhores cenas",
    "character": "Atsuya-Kusakabe",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?UP7kAtZt",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448551670.4236,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Atsuya Kusakabe - todas as cenas",
    "character": "Atsuya-Kusakabe",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?0yEUkg5w",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448551710.3364,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Choso Kamo - melhores cenas",
    "character": "Choso-Kamo",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?qGzKtxoM",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448551785.5652,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Choso Kamo - todas as cenas",
    "character": "Choso-Kamo",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?Cj2yKb7N",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448551872.772,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Fumihiko Takaba - melhores cenas",
    "character": "Fumihiko-Takaba",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?S5oS20mY",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448551899.7126,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Fumihiko Takaba - todas as cenas",
    "character": "Fumihiko-Takaba",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?SBJd1S6J",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448551925.9243,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hajime Kashimo - melhores cenas",
    "character": "Hajime-Kashimo",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?yfbeDe8g",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448551950.9668,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hajime Kashimo - todas as cenas",
    "character": "Hajime-Kashimo",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?RaotrZu6",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554648.6604,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hajime Kashimo - all scenes",
    "character": "Hajime-Kashimo",
    "language": "jp",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://loot-link.com/s?J1kLZFFF",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773682644775.0583,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hajime Kashimo - best scenes",
    "character": "Hajime-Kashimo",
    "language": "jp",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://lootdest.org/s?z0dQPd2w",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773682649644.9868,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hajime Kashimo - all scenes",
    "character": "Hajime-Kashimo",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?l5IRT0Yo",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773682398368.391,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hajime Kashimo - best scenes",
    "character": "Hajime-Kashimo",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://lootdest.org/s?xipfFp19",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773682402896.6987,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hiromi Higuruma - melhores cenas",
    "character": "Hiromi-Higuruma",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?6ypAqB2g",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774751106685.7627,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hiromi Higuruma - todas as cenas",
    "character": "Hiromi-Higuruma",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?B4PFjsDO",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774828406995.495,
    "updatedAtText": "3/29/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hiromi Higuruma - all scenes",
    "character": "Hiromi-Higuruma",
    "language": "jp",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?H6nZVh34",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774828387075.7146,
    "updatedAtText": "3/29/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hiromi Higuruma - best scenes",
    "character": "Hiromi-Higuruma",
    "language": "jp",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?oY0qQhQa",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774828374736.0952,
    "updatedAtText": "3/29/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hiromi Higuruma - all scenes",
    "character": "Hiromi-Higuruma",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?fDor9fis",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774828362708.964,
    "updatedAtText": "3/29/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Hiromi Higuruma - best scenes",
    "character": "Hiromi-Higuruma",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?QPd9RslV",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774828347838.3289,
    "updatedAtText": "3/29/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Jin Itadori - todas as cenas",
    "character": "Jin-Itadori",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?szMzQTlm",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554683.757,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kaori Itadori - todas as cenas",
    "character": "Kaori-Itadori",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?ERJb44Pl",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554691.5164,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kenjaku - all scenes",
    "character": "Kenjaku",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://loot-link.com/s?zt9IDwRp",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554723.289,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kenjaku - best scenes",
    "character": "Kenjaku",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?VvuynRNp",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554730.879,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kinji Hakari - melhores cenas",
    "character": "Kinji-Hakari",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?vzQuwPYL",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773685955921.8064,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kinji Hakari - todas as cenas",
    "character": "Kinji-Hakari",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?XOHsZ3no",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773691812851.163,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kinji Hakari - all scenes",
    "character": "Kinji-Hakari",
    "language": "jp",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?kWKE5782",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773685712337.6812,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kinji Hakari - best scenes",
    "character": "Kinji-Hakari",
    "language": "jp",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?ZCtFXNqz",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773685791805.6858,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kinji Hakari - all scenes",
    "character": "Kinji-Hakari",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?FIj8IJws",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773687267553.6338,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kinji Hakari - best scenes",
    "character": "Kinji-Hakari",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://lootdest.org/s?xsHgPh40",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773691374954.3577,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kirara Hoshi - melhores cenas",
    "character": "Kirara-Hoshi",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?xLF97fhV",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554782.3118,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kirara Hoshi - todas as cenas",
    "character": "Kirara-Hoshi",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?PfpAUFFE",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554794.2295,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kirara Hoshi - all scenes",
    "character": "Kirara-Hoshi",
    "language": "jp",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?Cu96SYyr",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773698878755.4446,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kirara Hoshi - best scenes",
    "character": "Kirara-Hoshi",
    "language": "jp",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?4rxHIlna",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773699026048.8916,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kirara Hoshi - all scenes",
    "character": "Kirara-Hoshi",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://loot-link.com/s?fdd6aizi",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773698566726.2393,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Kirara Hoshi - best scenes",
    "character": "Kirara-Hoshi",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://lootdest.org/s?De8JtQwU",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773698758243.2122,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Mai Zenin - melhores cenas",
    "character": "Mai-Zenin",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?xKzK61fx",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554836.7493,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Mai Zenin - todas as cenas",
    "character": "Mai-Zenin",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?ctc4B7p5",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554841.468,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Maki Zenin - melhores cenas",
    "character": "Maki-Zenin",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?jkvqlSG8",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554856.8567,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Maki Zenin - todas as cenas",
    "character": "Maki-Zenin",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?ZgkvuYv5",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554869.4097,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Masamichi Yaga - melhores cenas",
    "character": "Masamichi-Yaga",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?gIuOAMnC",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554873.0642,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Masamichi Yaga - todas as cenas",
    "character": "Masamichi-Yaga",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?2MBdJAaB",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554878.7373,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Megumi Fushiguro - melhores cenas",
    "character": "Megumi-Fushiguro",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?BYe3EiFg",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773537934874.203,
    "updatedAtText": "3/14/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Megumi Fushiguro - todas as cenas",
    "character": "Megumi-Fushiguro",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?5uWSYQKD",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773536933777.98,
    "updatedAtText": "3/14/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Megumi Fushiguro - all scenes",
    "character": "Megumi-Fushiguro",
    "language": "jp",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://loot-link.com/s?ALZwJ9zD",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773595609036.3108,
    "updatedAtText": "3/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Megumi Fushiguro - best scenes",
    "character": "Megumi-Fushiguro",
    "language": "jp",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?Tf7FGXOQ",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773699655044.12,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Megumi Fushiguro - all scenes",
    "character": "Megumi-Fushiguro",
    "language": "us",
    "season": "Season 3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?Zc0jpr8A",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773553975525.798,
    "updatedAtText": "3/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Megumi Fushiguro - best scenes",
    "character": "Megumi-Fushiguro",
    "language": "us",
    "season": "Season 3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://lootdest.org/s?XgszWqUC",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773554039461.2322,
    "updatedAtText": "3/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Naoya Zenin - melhores cenas",
    "character": "Naoya-Zenin",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?zcDzUb76",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554949.6162,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Naoya Zenin - todas as cenas",
    "character": "Naoya-Zenin",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?oUD10krR",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554961.8445,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Panda - melhores cenas",
    "character": "Panda",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?a4EMzzzn",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554965.5496,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Panda - todas as cenas",
    "character": "Panda",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?BhvwixUF",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554969.296,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Remi - melhores cenas",
    "character": "Remi",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?5mScYdVS",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773550953619.5298,
    "updatedAtText": "3/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Remi - todas as cenas",
    "character": "Remi",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?usohRUvk",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773711482563.4492,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Remi - all scenes",
    "character": "Remi",
    "language": "jp",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://loot-link.com/s?YDdrLMYr",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773547260910.6006,
    "updatedAtText": "3/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Remi - best scenes",
    "character": "Remi",
    "language": "jp",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?LQHlQGUL",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773547298709.4365,
    "updatedAtText": "3/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Remi - all scenes",
    "character": "Remi",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://loot-link.com/s?vPF3A0IO",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773711260401.5425,
    "updatedAtText": "3/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Remi - best scenes",
    "character": "Remi",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?DxTYXpgc",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773550886743.3733,
    "updatedAtText": "3/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Ryomen Sukuna - todas as cenas",
    "character": "Ryomen-Sukuna",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?QwjEwGbs",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554988.9578,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Saturo Gojo - flashback",
    "character": "Saturo-Gojo",
    "language": "br",
    "season": "Temporada-3",
    "pack": "flashback",
    "file": "flashback",
    "href": "https://loot-link.com/s?kSdzlRWX",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554974.5723,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Saturo Gojo - todas as cenas",
    "character": "Saturo-Gojo",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?nrbmqnL9",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554978.6694,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Shoko Leiri - todas as cenas",
    "character": "Shoko-Leiri",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?4kujGBgU",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448554983.5017,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Toji Fushiguro - melhores cenas",
    "character": "Toji-Fushiguro",
    "language": "br",
    "season": "temporada-2",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?qu8dueOc",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448555029.609,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Toji Fushiguro - todas as cenas",
    "character": "Toji-Fushiguro",
    "language": "br",
    "season": "temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?VetOjwNx",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448555074.7935,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Toji Fushiguro - Flashback",
    "character": "Toji-Fushiguro",
    "language": "br",
    "season": "Temporada-3",
    "pack": "Flashback",
    "file": "Flashback",
    "href": "https://loot-link.com/s?SUaXnugX",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448555078.0176,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Toji Fushiguro - melhores cenas",
    "character": "Toji-Fushiguro",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?8xNGCng5",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448555082.8716,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Toji Fushiguro - todas as cenas",
    "character": "Toji-Fushiguro",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?RrxYhdoc",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448555086.9268,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuji Itadori - melhores cenas",
    "character": "Yuji-Itadori",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?Y0Qu9cWV",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1775137627234.396,
    "updatedAtText": "4/2/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuji Itadori - todas as cenas",
    "character": "Yuji-Itadori",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?Zjf9DKHa",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1775137600465.5034,
    "updatedAtText": "4/2/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuji Itadori - all scenes",
    "character": "Yuji-Itadori",
    "language": "jp",
    "season": "season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://loot-link.com/s?lEFsH7ok",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1775138809898.22,
    "updatedAtText": "4/2/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuji Itadori - best scenes",
    "character": "Yuji-Itadori",
    "language": "jp",
    "season": "season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?jAslVxhn",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1775138854033.2466,
    "updatedAtText": "4/2/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuji Itadori - all scenes",
    "character": "Yuji-Itadori",
    "language": "us",
    "season": "season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?UpgDN7JN",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1775139856994.6707,
    "updatedAtText": "4/2/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuji Itadori - best scenes",
    "character": "Yuji-Itadori",
    "language": "us",
    "season": "season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?PNSdkwf3",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1775139883962.0408,
    "updatedAtText": "4/2/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuki Tsukumo - melhores cenas",
    "character": "Yuki-Tsukumo",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?mLJeycFJ",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448555151.5698,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuki Tsukumo - todas as cenas",
    "character": "Yuki-Tsukumo",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?0Rx1Si3S",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448555158.941,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuta Okkotsu - melhores cenas",
    "character": "Yuta-Okkotsu",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?pGNtcgiu",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448555172.5073,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "anime",
    "mediaSlug": "jujutsu-kaisen",
    "title": "Yuta Okkotsu - todas as cenas",
    "character": "Yuta-Okkotsu",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?Jwn3c3Yb",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448555187.0393,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Cassie Howard - melhores cenas",
    "character": "Cassie-Howard",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?Eu3MmIQk",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1777079850989.5825,
    "updatedAtText": "4/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Cassie Howard - todas as cenas",
    "character": "Cassie-Howard",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?uSVVDDkh",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1777079811078.678,
    "updatedAtText": "4/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Cassie Howard - all scenes",
    "character": "Cassie-Howard",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?3FCdORqf",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1777080228449.9404,
    "updatedAtText": "4/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Cassie Howard - best scenes",
    "character": "Cassie-Howard",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://lootdest.org/s?QOcF34fW",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1777080259068.7317,
    "updatedAtText": "4/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Daisy Miller - melhores cenas",
    "character": "Daisy-Miller",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?ONJTSuaI",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776816394202.6223,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Daisy Miller - todas as cenas",
    "character": "Daisy-Miller",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?8V4Qly2n",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776816462035.2043,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Daisy Miller - all scenes",
    "character": "Daisy-Miller",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?KxPnDGMj",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776816631670.9434,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Daisy Miller - best scenes",
    "character": "Daisy-Miller",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://lootdest.org/s?2pPBOFSy",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776816550582.5664,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Lexi Howard - melhores cenas",
    "character": "Lexi-Howard",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?HdQzvSDx",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1777065081555.4597,
    "updatedAtText": "4/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Lexi Howard - todas as cenas",
    "character": "Lexi-Howard",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?bLoP1xOh",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1777065034799.322,
    "updatedAtText": "4/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Lexi Howard - all scenes",
    "character": "Lexi-Howard",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?IdTXybPs",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1777070811779.2112,
    "updatedAtText": "4/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Lexi Howard - best scenes",
    "character": "Lexi-Howard",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?Vgx6hrld",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1777070841791.1306,
    "updatedAtText": "4/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Maddy Perez - melhores cenas",
    "character": "Maddy-Perez",
    "language": "br",
    "season": "Temporada-1",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?MQZthTLp",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776279930102.1597,
    "updatedAtText": "4/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Maddy Perez - todas as cenas",
    "character": "Maddy-Perez",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?IxxXX5jq",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776292961059.359,
    "updatedAtText": "4/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Maddy Perez - melhores cenas",
    "character": "Maddy-Perez",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?KvrgSngb",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776783582633.9897,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Maddy Perez - todas as cenas",
    "character": "Maddy-Perez",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?37jvww10",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776783575417.3223,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Maddy Perez - all scenes",
    "character": "Maddy-Perez",
    "language": "us",
    "season": "Season-1",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://loot-link.com/s?0ogNQVNn",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776290514054.4937,
    "updatedAtText": "4/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Maddy Perez - best scenes",
    "character": "Maddy-Perez",
    "language": "us",
    "season": "Season-1",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://lootdest.org/s?UeoiR9lt",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776279714457.7021,
    "updatedAtText": "4/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Maddy Perez - all scenes",
    "character": "Maddy-Perez",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?sjuzLNdU",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776783683174.1267,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Maddy Perez - best scenes",
    "character": "Maddy-Perez",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?vVDYLsVI",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776783658041.2705,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Rue Bennett - melhores cenas",
    "character": "Rue-Bennett",
    "language": "br",
    "season": "Temporada-3",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?4JvQsa1u",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776813104584.035,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Rue Bennett - todas as cenas",
    "character": "Rue-Bennett",
    "language": "br",
    "season": "Temporada-3",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?adPNXIZ3",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776812930508.7363,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Rue Bennett - all scenes",
    "character": "Rue-Bennett",
    "language": "us",
    "season": "Season-3",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://loot-link.com/s?cIcX7uA5",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776814500627.8728,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "euphoria",
    "title": "Rue Bennett - best scenes",
    "character": "Rue-Bennett",
    "language": "us",
    "season": "Season-3",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?f6OiR55Z",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776814657256.2048,
    "updatedAtText": "4/21/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "kakegurui",
    "title": "Yumeko - melhores cenas",
    "character": "Yumeko",
    "language": "br",
    "season": "Temporada-1",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?tC2LZvxa",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776291659608.886,
    "updatedAtText": "4/15/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "kakegurui",
    "title": "Yumeko - todas as cenas",
    "character": "Yumeko",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?bvMtc777",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1768792813979.7751,
    "updatedAtText": "1/18/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "outer-banks",
    "title": "Jj Maybank - melhores cenas",
    "character": "Jj-Maybank",
    "language": "br",
    "season": "Temporada-1",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?N3D1Yw74",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743070.038,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "outer-banks",
    "title": "Jj Maybank - todas as cenas",
    "character": "Jj-Maybank",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?F449aInr",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743097.481,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "067 - melhores cenas",
    "character": "067",
    "language": "br",
    "season": "Temporada-1",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?gM1uJEIA",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774461214791.7683,
    "updatedAtText": "3/25/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "067 - todas as cenas",
    "character": "067",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?zhXKAtck",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278217.973,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "222 - melhores cenas",
    "character": "222",
    "language": "br",
    "season": "Temporada-2",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?jSbVNsmV",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278244.0608,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "222 - todas as cenas",
    "character": "222",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?DwbA26rW",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278268.3862,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "240 - todas as cenas",
    "character": "240",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?nnsOymfZ",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278292.4673,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "456 - melhores cenas",
    "character": "456",
    "language": "br",
    "season": "Temporada-1",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?AEZmP0rB",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278318.1995,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "456 - todas as cenas",
    "character": "456",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?8pDZ6MrI",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278344.218,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "Front Man - melhores cenas",
    "character": "Front Man",
    "language": "br",
    "season": "Temporada-1",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?Cn1BfUUz",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278380.4226,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "Front Man - todas as cenas",
    "character": "Front Man",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?Yp9q040w",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278404.6177,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "Hwang Jun ho - melhores cenas",
    "character": "Hwang Jun-ho",
    "language": "br",
    "season": "Temporada-1",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?uknk7mQI",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278430.3628,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "Hwang Jun ho - todas as cenas",
    "character": "Hwang Jun-ho",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?TipHnXiW",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278458.9556,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "squid-game",
    "title": "Salesman - todas as cenas",
    "character": "Salesman",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?kaBtLP1C",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774403278483.3767,
    "updatedAtText": "3/24/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Holly Wheeler - todas as cenas",
    "character": "Holly-Wheeler",
    "language": "br",
    "season": "Temporada-5",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?JpZb5MI8",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774666859587.9727,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Karen Wheeler - todas as cenas",
    "character": "Karen-Wheeler",
    "language": "br",
    "season": "Temporada-5",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?Sxnn92ba",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774667077479.4788,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Max Mayfield - melhores cenas",
    "character": "Max-Mayfield",
    "language": "br",
    "season": "Temporada-5",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?goTGwrgK",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774667173998.422,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Max Mayfield - todas as cenas",
    "character": "Max-Mayfield",
    "language": "br",
    "season": "Temporada-5",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?xw8nKS2g",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774666998334.672,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Mike Wheeler - todas as cenas",
    "character": "Mike-Wheeler",
    "language": "br",
    "season": "Temporada-5",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?xiX5PmFF",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774666956710.5325,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Robin Buckley - todas as cenas",
    "character": "Robin-Buckley",
    "language": "br",
    "season": "Temporada-5",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?wQuGR1w3",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774667027109.9702,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Steve Harrington - todas as cenas",
    "character": "Steve-Harrington",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?I0mqLbGA",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774666009650.1548,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Steve Harrington - todas as cenas",
    "character": "Steve-Harrington",
    "language": "br",
    "season": "Temporada-5",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?RFAGYqMN",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774666688749.4385,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Will Byers - melhores cenas",
    "character": "Will-Byers",
    "language": "br",
    "season": "Temporada-5",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?Mp7gmpKd",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774667136637.7031,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "stranger-things",
    "title": "Will Byers - todas as cenas",
    "character": "Will-Byers",
    "language": "br",
    "season": "Temporada-5",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?7U143k1X",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774667122039.252,
    "updatedAtText": "3/27/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "the-vampire-diaries",
    "title": "Damon Salvatore - todas as cenas",
    "character": "Damon-Salvatore",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?lzKXi8ip",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774491161969.388,
    "updatedAtText": "3/25/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "the-vampire-diaries",
    "title": "ep 7 - melhores cenas",
    "character": "ep-7",
    "language": "br",
    "season": "Temporada-1",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?qikPfaur",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774487558093.0493,
    "updatedAtText": "3/25/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "the-vampire-diaries",
    "title": "ep 7 - todas as cenas",
    "character": "ep-7",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?7u92znGW",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774487714876.712,
    "updatedAtText": "3/25/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Agnes DeMille - todas as cenas",
    "character": "Agnes-DeMille",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?pWKw7N3i",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743157.9316,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Ajax Petropolus - todas as cenas",
    "character": "Ajax-Petropolus",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?sWE4FjNB",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743209.9707,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Bianca Barclay - todas as cenas",
    "character": "Bianca-Barclay",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?vvwXEqtx",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743262.5784,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Bruno Yuson - todas as cenas",
    "character": "Bruno-Yuson",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?XdR8zYsR",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743316.4895,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Dra. Rachael Fairbun - todas as cenas",
    "character": "Dra.-Rachael-Fairbun",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?xY6ffoma",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743347.3079,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Enid Sinclair - Enid no corpo da Wandinha",
    "character": "Enid-Sinclair",
    "language": "br",
    "season": "Temporada-2",
    "pack": "Enid-no-corpo-da-Wandinha",
    "file": "Enid-no-corpo-da-Wandinha",
    "href": "https://loot-link.com/s?sCT78KRZ",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773521061210.3503,
    "updatedAtText": "3/14/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Enid Sinclair - todas as cenas",
    "character": "Enid-Sinclair",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?gicD9b9X",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743453.3806,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Enid Sinclair - Wandinha no corpo da Enid",
    "character": "Enid-Sinclair",
    "language": "br",
    "season": "Temporada-2",
    "pack": "Wandinha-no-corpo-da-Enid",
    "file": "Wandinha-no-corpo-da-Enid",
    "href": "https://lootdest.org/s?2w20UXnj",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773521076726.438,
    "updatedAtText": "3/14/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Eugene Ottinger - todas as cenas",
    "character": "Eugene-Ottinger",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?0qGn2O7s",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743504.6323,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Gomez Addams - todas as cenas",
    "character": "Gomez-Addams",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?USs0Obes",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743530.8054,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Goody Addams - todas as cenas",
    "character": "Goody-Addams",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?9YPHuO84",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743557.9373,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Isaac Night (slurp) - todas as cenas",
    "character": "Isaac-Night-(slurp)",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?tlySnsgz",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743583.9958,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Isadora Capri - todas as cenas",
    "character": "Isadora-Capri",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?zWHSqUAm",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743643.6492,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Larissa Weems - todas as cenas",
    "character": "Larissa-Weems",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?Q3GcnNyN",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743670.3516,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Maozinha - todas as cenas",
    "character": "Maozinha",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?qrcqnTLz",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743697.1577,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Mortícia Addams - todas as cenas",
    "character": "Mortícia-Addams",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?AdXIwwRQ",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743750.0896,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Pugsley Addams - todas as cenas",
    "character": "Pugsley-Addams",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?blZL86fL",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743802.4858,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Rosaline Rotwood - todas as cenas",
    "character": "Rosaline-Rotwood",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?VgIKhx0d",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743829.135,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Tyler Galpin - todas as cenas",
    "character": "Tyler-Galpin",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?Ci2AemCJ",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743915.5935,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Vovó Addams - todas as cenas",
    "character": "Vovó-Addams",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?YYYbLDRc",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448743972.2334,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Wednesday Addams - melhores cenas",
    "character": "Wednesday-Addams",
    "language": "br",
    "season": "Temporada-1",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?gYiUgO11",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448744023.6753,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Wednesday Addams - todas as cenas",
    "character": "Wednesday-Addams",
    "language": "br",
    "season": "Temporada-1",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?AOdeDSB6",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448744136.8567,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Wednesday Addams - melhores cenas",
    "character": "Wednesday-Addams",
    "language": "br",
    "season": "Temporada-2",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?FFI9Ealx",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448744164.6465,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Wednesday Addams - mudança de corpos",
    "character": "Wednesday-Addams",
    "language": "br",
    "season": "Temporada-2",
    "pack": "mudança-de-corpos",
    "file": "mudança-de-corpos",
    "href": "https://loot-link.com/s?HMz0TBYh",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448744225.68,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "series",
    "mediaSlug": "wednesday",
    "title": "Wednesday Addams - todas as cenas",
    "character": "Wednesday-Addams",
    "language": "br",
    "season": "Temporada-2",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?GgngW8C6",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448744305.4856,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "10-things-i-hate-about-you",
    "title": "Cameron - todas as cenas",
    "character": "Cameron",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?sUQ9BO6U",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774738681616.3633,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "10-things-i-hate-about-you",
    "title": "Kat - todas as cenas",
    "character": "Kat",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?dBfqRjFN",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774738681660.4106,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "10-things-i-hate-about-you",
    "title": "Patrick - todas as cenas",
    "character": "Patrick",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?jVH9tM9k",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774738681695.7634,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "challengers",
    "title": "Art Donaldson - todas as cenas",
    "character": "Art Donaldson",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?a3qHgD27",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448701461.596,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "challengers",
    "title": "Patrick Zweig - todas as cenas",
    "character": "Patrick Zweig",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?KRBbnhvt",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448701525.4946,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "challengers",
    "title": "Tashi Ducan - todas as cenas",
    "character": "Tashi Ducan",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?vkq6Lmfy",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1773448701555.3923,
    "updatedAtText": "3/13/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "culpa-mia",
    "title": "Nick Leister - melhores cenas",
    "character": "Nick Leister",
    "language": "br",
    "season": "",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?iaDsxJ3U",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774827861440.084,
    "updatedAtText": "3/29/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "culpa-mia",
    "title": "Nick Leister - todas as cenas",
    "character": "Nick Leister",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?UPueqtPk",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774827861483.3132,
    "updatedAtText": "3/29/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "culpa-mia",
    "title": "Noah Morgan - melhores cenas",
    "character": "Noah Morgan",
    "language": "br",
    "season": "",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://loot-link.com/s?QpqlhA8k",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774827861517.2676,
    "updatedAtText": "3/29/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "culpa-mia",
    "title": "Noah Morgan - todas as cenas",
    "character": "Noah Morgan",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?E4ubF0Pc",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774827861554.2712,
    "updatedAtText": "3/29/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "culpa-nuestra",
    "title": "Nick Leister - todas as cenas",
    "character": "Nick-Leister",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?UPueqtPk",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774986846271.2913,
    "updatedAtText": "3/31/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "culpa-nuestra",
    "title": "Noah Morgan - todas as cenas",
    "character": "Noah-Morgan",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?E4ubF0Pc",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774986858277.315,
    "updatedAtText": "3/31/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "culpa-nuestra",
    "title": "Sofia Zabala - todas as cenas",
    "character": "Sofia-Zabala",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?7Z1JbEzh",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774986962272.4229,
    "updatedAtText": "3/31/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "miller's-girl",
    "title": "Cairo Sweet - melhores cenas",
    "character": "Cairo-Sweet",
    "language": "br",
    "season": "",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?MIWwxeU8",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1775596442404.4106,
    "updatedAtText": "4/7/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "miller's-girl",
    "title": "Cairo Sweet - todas as cenas",
    "character": "Cairo-Sweet",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?bx4ENiCE",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1775596441216.8423,
    "updatedAtText": "4/7/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "shes-the-man",
    "title": "Duke Orsino - all scenes",
    "character": "Duke-Orsino",
    "language": "us",
    "season": "",
    "pack": "all-scenes",
    "file": "all-scenes",
    "href": "https://lootdest.org/s?LVb7RnO6",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776377655385.9841,
    "updatedAtText": "4/16/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "shes-the-man",
    "title": "Duke Orsino - best scenes",
    "character": "Duke-Orsino",
    "language": "us",
    "season": "",
    "pack": "best-scenes",
    "file": "best-scenes",
    "href": "https://loot-link.com/s?QGqU13FQ",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1776638366747.1753,
    "updatedAtText": "4/19/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "the-fallout",
    "title": "Amelia - todas as cenas",
    "character": "Amelia",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?F7G3H7CX",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774746217573.778,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "the-fallout",
    "title": "Mia - todas as cenas",
    "character": "Mia",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?aO15Ekzk",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774746217611.6506,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "the-fallout",
    "title": "Nick - todas as cenas",
    "character": "Nick",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?FHf3oFWh",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774746217715.8474,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "the-fallout",
    "title": "Quinton - todas as cenas",
    "character": "Quinton",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?r4UncfMk",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774746217746.5425,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "the-fallout",
    "title": "Vada Cavell - todas as cenas",
    "character": "Vada-Cavell",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?ZsBF2KXV",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774746217782.8623,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "twilight",
    "title": "Alice Cullen - todas as cenas",
    "character": "Alice-Cullen",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?r9TlX6JB",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774752121523.0134,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "twilight",
    "title": "Bella Swan - todas as cenas",
    "character": "Bella-Swan",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?L9L8dY85",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774752121564.1428,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "twilight",
    "title": "Edwaed Cullen - todas as cenas",
    "character": "Edwaed-Cullen",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://loot-link.com/s?UTBTBaXa",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774752121606.446,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "winter-spring-summer-or-fall",
    "title": "Remi Aguilar - melhores cenas",
    "character": "Remi Aguilar",
    "language": "br",
    "season": "",
    "pack": "melhores-cenas",
    "file": "melhores-cenas",
    "href": "https://lootdest.org/s?RvdjpUSP",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774747732476.7854,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  },
  {
    "mediaType": "movie",
    "mediaSlug": "winter-spring-summer-or-fall",
    "title": "Remi Aguilar - todas as cenas",
    "character": "Remi Aguilar",
    "language": "br",
    "season": "",
    "pack": "todas-as-cenas",
    "file": "todas-as-cenas",
    "href": "https://lootdest.org/s?pXPk1NV5",
    "fileSizeBytes": 0,
    "fileSizeText": "—",
    "updatedAt": 1774747535346.135,
    "updatedAtText": "3/28/2026",
    "isMonetized": true
  }
];
